---
- name: set-cluster
  ansible.builtint.shell: >
    {{ kubectl_bin_path }} config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"
  become: yes
  become_user: "{{ local_id }}"
  
- name: set-credentials
  ansible.builtint.shell: >
    {{ kubectl_bin_path }} config set-credentials system:kube-scheduler \
    --client-certificate=scheduler.pem \
    --client-key=scheduler-key.pem \
    --embed-certs=true \
    --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"

- name: set-context
  ansible.builtint.shell: >
    {{ kubectl_bin_path }} config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user=system:kube-scheduler \
    --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"

- name: use-context
  ansible.builtint.shell:
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    cmd: {{ kubectl_bin_path }} config use-context default --kubeconfig=kube-scheduler.kubeconfig
