- name: Create directory for kubeconfig files
  file:
    path: "{{ k8s_conf_files_dir }}"
    owner: "{{ local_id }}"
    group: "{{ local_id }}"
    #mode: "0440"
    state: directory
    #recurse: yes

- name: Generate encryption key
  shell:
    cmd: head -c 32 /dev/urandom | base64
  register: enckey

- name: Create encryption config file
  template:
    src: "templates/encryption-config.yaml.j2"
    dest: "{{ k8s_conf_files_dir }}/encryption-config.yaml"
    mode: "0600"
    owner: "{{ local_id }}"
    group: "{{ local_id }}"
  vars:
    k8s_encryption_config_key: "{{ enckey.stdout }}"