---
#
# Configure vbox host, generate tls certs, kubectl conf files
#
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  openssh_keypair:
    path: "/home/{{ local_id }}/.ssh/id_rsa_{{ user_id }}"
    owner: "{{ local_id }}"
    group: "{{ local_id }}"

- name: Fix owner of the generated pub key
  file:
    path: "/home/{{ local_id }}/.ssh/id_rsa_{{ user_id }}"
    owner: "{{ local_id }}"
    group: "{{ local_id }}"

- name: Get hosts for Kubernetes API cert
  set_fact:
    k8s_api_hosts: >-
      {% set comma = joiner(",") %}{% for item in groups['k8s_controller'] -%}
        {{ comma() }}{{ hostvars[item]["ansible_"+hostvars[item]["public_if"]].ipv4.address }}{{ comma() }}{{ hostvars[item]["ansible_"+hostvars[item]["private_if"]].ipv4.address }}{{ comma() }}{{ item }}
      {%- endfor %},{{ k8s_api_lb_ip }},127.0.0.1,kubernetes.default,10.32.0.1

- name: Output of hostnames/IPs used for Kubernetes API server certificate
  debug: var=k8s_api_hosts

- name: Get hosts for Kubernetes etcd cert
  set_fact:
    k8s_etcd_hosts: >-
      {% set comma = joiner(",") %}{% for item in groups['k8s_etcd'] -%}
        {{ comma() }}{{ hostvars[item]["ansible_"+hostvars[item]["public_if"]].ipv4.address }}{{ comma() }}{{ hostvars[item]["ansible_"+hostvars[item]["private_if"]].ipv4.address }}{{ comma() }}{{ item }}
      {%- endfor %},127.0.0.1

- name: Output of hostnames/IPs used for Kubernetes etcd server certificate
  debug: var=k8s_etcd_hosts

- name: Install cfssl and generate k8s TLS certs
  include_role:
    name: k8s-certs
  vars:
    k8s_cert_api_hosts: k8s_api_hosts
    k8s_cert_etcd_hosts: k8s_etcd_hosts
    k8s_cert_node_hosts: k8s_worker_nodes

- name: Generate encryption config
  import_tasks: encryption_key.yml

- name: kubelet config
  include_tasks: conf_kubelet.yml

- name: kube proxy config
  include_tasks: conf_kube-proxy.yml

- name: controller-manager config
  include_tasks: conf_cont-mgr.yml

- name: kube-scheduler config
  include_tasks: conf_kube-sched.yml

- name: kube admin config
  include_tasks: conf_admin.yml

- name: Fix owner of kube certs and conf files
  file:
    path: "{{ k8s_conf_files_dir }}"
    owner: "{{ local_id }}"
    group: "{{ local_id }}"
    mode: 0700

- name: Create nexus3 container for Docker image proxy
  tags: docker_proxy
  include_tasks: nexus.yml

- name: Create haproxy container for kube api load balancer
  tags: kube_api_lb
  include_tasks: kube_lb.yml
