---
- name: Download cfssl binaries
  get_url:
    url: "https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/{{ item }}_{{ cfssl_version }}_{{ cfssl_os }}_{{ cfssl_arch }}"
    dest: "{{ cfssl_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
    checksum: "sha256:{{ cfssl_checksum_url }}"
  with_items:
    - cfssl
    - cfssl-bundle
    - cfssl-certinfo
    - cfssl-newkey
    - cfssl-scan
    - cfssljson
    - mkbundle
    - multirootca