---
- name: Download containerd
  get_url:
    url: "{{ oci_containerd_url }}"
    dest: "/tmp/{{ oci_containerd_file }}"

- name: Extract containerd
  unarchive:
    src: "/tmp/{{ oci_containerd_file }}"
    remote_src: yes
    dest: /bin/
    extra_opts: [--strip-components=1]
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root

- name: Create containerd unit file
  copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service
  notify:
  - Reload systemd units
  - Restart containerd service
