---
# handlers file for oci
- name: Reload systemd units
  systemd:
    daemon_reload: yes

# containerd
- name: Extract containerd
  unarchive:
    src: "/tmp/{{ archives.containerd.file }}"
    remote_src: yes
    dest: /bin
    extra_opts: [--strip-components=1]
    mode: "u=rwx,g=rx,o=rx"
    owner: root
    group: root

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted