---
- name: Download kubectl binary (OSX amd64)
  get_url:
    url: "{{ kubectl_dl_url }}"
    dest: "/usr/local/bin/kubectl"
    mode: "o=rwx,g=rx,u=rx"
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"

- name: Autocompletion for zsh
  lineinfile:
    path: /Users/{{ kctl_user_id }}/.zshrc
    line: source <(kubectl completion zsh)
    insertbefore: BOF
  when: kctl_shell_type == 'zsh'