---
- name: Download kubectl binary (Linux amd64)
  get_url:
    url: "{{ kubectl_dl_url }}"
    dest: "/usr/local/bin/"
    mode: "u=rwx,g=rx,o=rx"
    owner: root
    group: root

- name: Download helm binary (Linux amd64)
  get_url:
    url: "{{ helm_dl_url }}"
    dest: /tmp
  notify: Extract Helm

#source /usr/share/bash-completion/bash_completion
