apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-one
spec:
  selector:
    matchLabels:
      system: DaemonSetOne
  updateStrategy:
    type: OnDelete 
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        system: DaemonSetOne
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
