apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-roll
spec:
  selector:
    matchLabels:
      system: DaemonSetRoll
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        system: DaemonSetRoll
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
