kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-one
  namespace: diehlabs
  labels:
    system: secondary
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      deploy: secondary
  template:
    metadata:
      labels:
        deploy: secondary
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.4-alpine
          ports:
          - containerPort: 80
            protocol: TCP
      nodeSelector:
        system: secondOne
