kind: PersistentVolume
apiVersion: v1
metadata:
    name: nfs-pv
    labels:
      type: local
      nfsvol: nfs01
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteOnce
    mountOptions:
      - hard
      - nfsvers=4.1
    nfs:
      path: /export/ssd/data/k8s-test
      server: 192.168.1.10
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-claim
  labels:
    nfsvol: nfs01
spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: busybox-nfs
    labels:
    app: busybox
    nfsvol: nfs01
spec:
    replicas: 1
    selector:
    matchLabels:
        deploy: example
    template:
    metadata:
        labels:
        deploy: example
    spec:
        containers:
        - name: busybox
            image: busybox:latest
            command:
            - sleep
            - "6000"
            volumeMounts:
            - name: nfs-pv
                mountPath: /data
        restartPolicy: Always
        volumes:
        - name: nfs-pv
            persistentVolumeClaim:
            claimName: busybox-nfs
    