kind: PersistentVolume
apiVersion: v1
metadata:
    name: nfs-pv
    labels: 
        type: local 
spec:
    capacity: 
        storage: 2Gi
    accessModes:
        - ReadWriteOnce
    mountOptions:
      - hard
      - nfsvers=4.1
    nfs:
      path: /mnt/ssd/data/k8s-test
      server: 192.168.1.10
