kind: Deployment
apiVersion: apps/v1
metadata:
  name: busybox-nfs
  labels:
    app: busybox
    nfsvol: nfs01
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: example
  template:
    metadata:
      labels:
        deploy: example
    spec:
      containers:
        - name: busybox
          image: busybox:latest
