---
  # https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/8fd6380bbc92137f8d1cb62f00865f1b3c681d3c/docs/11-pod-network-routes.md#the-routing-table
- name: Create netplan 50-vagrant.yaml
  template:
      src: 50-vagrant.yaml.j2
      dest: /etc/netplan/50-vagrant.yaml
  notify:
  - Netplan apply