---
- name: Perform system conf tasks
  include_tasks: conf.yml
  tags:
  - node

- name: Manage IP routes
  include_tasks: ip_routes.yml

- name: Copy kube conf files
  copy:
    src: "{{ k8s_conf_files_dir }}/{{ item }}"
    dest: /home/vagrant
  loop: 
    - "{{ inventory_hostname_short }}.kubeconfig"
    - kube-proxy.kubeconfig
  tags:
  - node

- name: Download and configure CNI plugins
  include_tasks: cni.yml
  tags:
  - cni

- name: Download and configure containerd
  include_role:
    name: k8s-oci
  tags:
  - oci

- name: Configure kubelet
  include_tasks: kubelet.yml

- name: Configure kube-proxy
  include_tasks: kube-proxy.yml