---
# handlers file for k8s-worker
- name: Reload systemd units
  systemd:
    daemon_reload: yes

- name: Netplan apply
  shell:
    cmd: netplan apply
  
# containerd
- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: reload sysctl
  shell: sysctl --system
