---
# handlers file for k8s-worker
- name: Reload systemd units
  systemd:
    daemon_reload: yes

# containerd
- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: reload sysctl
  shell: sysctl --system

# CNI
- name: Extract cni plugins
  unarchive:
    src: "/tmp/cni-plugins-linux-amd64-v{{ versions.cni_plugins }}.tgz"
    remote_src: yes
    dest: /opt/cni/bin
    extra_opts: [--strip-components=1]
    mode: u=rwx,g=rx,o=rx"
    owner: root
    group: root