---
# handlers file for k8s-worker
- name: Reload systemd units
  systemd:
    daemon_reload: yes

# containerd
- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted

