---

#--------------------------------------------------------------------------------------------------------
# Configuration for all hosts
#--------------------------------------------------------------------------------------------------------
- hosts:
  # - k8s_controller
  # - localhost
  - all
  become: yes
  tags: 
    - base
    - etcd
    - control_plane
  tasks:
    # Create hosts files on all systems - Required for kube dns to function
    - name: add hosts to hosts
      tags: hostsfile
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_'+private_if].ipv4.address }} {{ hostvars[item].inventory_hostname_short }}" #" {{ hostvars[item].inventory_hostname }}"
      loop: "{{ groups['k8s_controller'] | union(groups['k8s_node']) | union(groups['k8s_etcd']) }}"

#--------------------------------------------------------------------------------------------------------
# Configure vbox host, generate tls certs, kubectl conf files
#--------------------------------------------------------------------------------------------------------
- hosts: localhost
  become: yes
  tags:
    - base
    - certs
  vars:
    docker_group_members:
      - "{{ local_id }}"
  tasks:
    - name: Gather facts
      tags: always
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_controller'] | union(groups['k8s_node']) | union(groups['k8s_etcd']) }}"

    - name: Configure host system components
      include_role:
        name: vbox-host

    - name: Install kube tools
      include_role:
        name: kubetools
      vars:
        kubectl_version: "{{ k8s_version }}"
        kctl_user_id: "{{ local_id }}"

#--------------------------------------------------------------------------------------------------------
# Deploy etcd cluster
#--------------------------------------------------------------------------------------------------------
- hosts: k8s_etcd
  become: yes
  roles:
  - role: k8s-etcd
    tags:
      - etcd

#--------------------------------------------------------------------------------------------------------
# Deploy control plane components
#--------------------------------------------------------------------------------------------------------
- hosts: k8s_controller
  become: yes
  tags:
  - control_plane
  tasks:
    - name: Get hosts for etcd initial cluster
      set_fact:
        k8sEtcdHosts: >-
          {% set comma = joiner(",") %}{% for item in groups['k8s_etcd'] -%}
            {{ comma() }}https://{{ hostvars[item]["ansible_"+hostvars[item]["private_if"]].ipv4.address }}:2379
          {%- endfor %}

    - name: Output of hostnames/IPs used for etcd initial cluster
      debug: var=k8sEtcdHosts

    - name: Configure vbox specifics
      tags:
      - control_plane
      import_role:
        name: k8s-vbox-config
      vars:
        k8s_vbox_config_vm_pub_net_cidr: "{{ vm_pub_net_cidr }}"
        k8s_vbox_config_public_if: "{{ hostvars[inventory_hostname_short]['public_if'] }}"
        k8s_vbox_config_private_if: "{{ hostvars[inventory_hostname_short]['private_if'] }}"
        k8s_vbox_config_controller: true

    - name: Install and configure controller services
      tags:
      - control_plane
      import_role:
        name: k8s-controller
      vars:
        k8s_etcd_hosts: "{{ k8sEtcdHosts }}"

#--------------------------------------------------------------------------------------------------------
# Configure worker nodes
#--------------------------------------------------------------------------------------------------------
- hosts:
  - k8s_node

  become: yes
  tags:
  - nodes
  tasks:
    # - name: Gather facts
    #   tags: always
    #   setup:
    #   delegate_to: "{{ item }}"
    #   delegate_facts: True
    #   loop: "{{ groups['k8s_controller'] | union(groups['k8s_node']) }}"
    - name: Configure vbox specifics
      import_role:
        name: k8s-vbox-config
      vars:
        k8s_vbox_config_vm_pub_net_cidr: "{{ vm_pub_net_cidr }}"
        k8s_vbox_config_public_if: "{{ hostvars[inventory_hostname_short]['public_if'] }}"
        k8s_vbox_config_private_if: "{{ hostvars[inventory_hostname_short]['private_if'] }}"
        k8s_vbox_config_nodes_group: "{{ groups['k8s_node'] | union(groups['k8s_controller']) }}"

    - name: Install and configure node services
      include_role:
        name: k8s-node

#--------------------------------------------------------------------------------------------------------
# Deploy coredns, rbac
#--------------------------------------------------------------------------------------------------------
- hosts: localhost
  become: yes
  tags:
  - deployments
  roles:
  - role: k8s-deployments