---
- name: Install kube-apiserver binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-apiserver"
    dest: /usr/local/bin
    mode: u=rx,g=rx,o=r
    owner: root
    group: root
  notify: Restart kube-apiserver service

- name: Create API server unit file
  ansible.builtin.template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  notify:
    - Restart kube-apiserver service
    - Reload systemd units

- name: Enable and start kube-apiserver service
  ansible.builtin.systemd:
    name: kube-apiserver
    enabled: yes
    state: started
