---
- name: Install kube-scheduler binaries
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-scheduler"
    dest: /usr/local/bin
    mode: u=rx,g=rx,o=r
    owner: root
    group: root
  notify: Restart kube-scheduler service

- name: Create kube scheduler unit file
  ansible.builtin.template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
  notify:
    - Restart kube-scheduler service
    - Reload systemd units

- name: Enable and start kube-scheduler service
  ansible.builtin.systemd:
    name: kube-scheduler
    enabled: yes
    state: started
