galaxy_info:
  author: Chris Diehl
  description: Installs cfssl and generates TLS certs for Kubernetes
  company: Diehlabs
  license: GPL-2.0
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
    - all

  galaxy_tags: []

dependencies:

  